steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    if [[ "$BRANCH_NAME" == "master" ]]
    then
        echo "Run master task"
    else
        echo "Run branch"
    fi
